/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HostCodeRouteImport } from './routes/host.$code'
import { Route as PlayCodeRouteImport } from './routes/play.$code'
import { Route as SorularIndexRouteImport } from './routes/sorular.index'
import { Route as SorularSetIdRouteImport } from './routes/sorular.$setId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostCodeRoute = HostCodeRouteImport.update({
  id: '/host/$code',
  path: '/host/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayCodeRoute = PlayCodeRouteImport.update({
  id: '/play/$code',
  path: '/play/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const SorularIndexRoute = SorularIndexRouteImport.update({
  id: '/sorular/',
  path: '/sorular/',
  getParentRoute: () => rootRouteImport,
} as any)
const SorularSetIdRoute = SorularSetIdRouteImport.update({
  id: '/sorular/$setId',
  path: '/sorular/$setId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/host/$code': typeof HostCodeRoute
  '/play/$code': typeof PlayCodeRoute
  '/sorular/$setId': typeof SorularSetIdRoute
  '/sorular/': typeof SorularIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/host/$code': typeof HostCodeRoute
  '/play/$code': typeof PlayCodeRoute
  '/sorular/$setId': typeof SorularSetIdRoute
  '/sorular': typeof SorularIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/host/$code': typeof HostCodeRoute
  '/play/$code': typeof PlayCodeRoute
  '/sorular/$setId': typeof SorularSetIdRoute
  '/sorular/': typeof SorularIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/host/$code' | '/play/$code' | '/sorular/$setId' | '/sorular/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/host/$code' | '/play/$code' | '/sorular/$setId' | '/sorular'
  id:
    | '__root__'
    | '/'
    | '/host/$code'
    | '/play/$code'
    | '/sorular/$setId'
    | '/sorular/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HostCodeRoute: typeof HostCodeRoute
  PlayCodeRoute: typeof PlayCodeRoute
  SorularSetIdRoute: typeof SorularSetIdRoute
  SorularIndexRoute: typeof SorularIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$code': {
      id: '/host/$code'
      path: '/host/$code'
      fullPath: '/host/$code'
      preLoaderRoute: typeof HostCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$code': {
      id: '/play/$code'
      path: '/play/$code'
      fullPath: '/play/$code'
      preLoaderRoute: typeof PlayCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorular/': {
      id: '/sorular/'
      path: '/sorular'
      fullPath: '/sorular/'
      preLoaderRoute: typeof SorularIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorular/$setId': {
      id: '/sorular/$setId'
      path: '/sorular/$setId'
      fullPath: '/sorular/$setId'
      preLoaderRoute: typeof SorularSetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HostCodeRoute: HostCodeRoute,
  PlayCodeRoute: PlayCodeRoute,
  SorularSetIdRoute: SorularSetIdRoute,
  SorularIndexRoute: SorularIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
